apiVersion: apps/v1
kind: Deployment
metadata:
  name: igokochi-auth-deployment
  labels:
    app: igokochi-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igokochi-auth
  template:
    metadata:
      labels:
        app: igokochi-auth
    spec:
      containers:
        - name: igokochi-auth
          image: ricoharsono/huatah-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: JWT_SECRET
              value: "Daveisthebest"
            - name: DB_HOST
              value: "mysql-igokochi-service.default.svc.cluster.local"
            - name: DB_USER
              value: "igokochi_user"
            - name: DB_PASSWORD
              value: "igokochi_pass"
            - name: DB_NAME
              value: "igokochi"
---
apiVersion: v1
kind: Service
metadata:
  name: igokochi-auth-service
spec:
  type: ClusterIP
  selector:
    app: igokochi-auth
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
